const KEY="vitrinouData";let data=JSON.parse(localStorage.getItem(KEY))||{settings:{name:"Vitrinou",title:"Confira nossos produtos",text:"Escolha seus produtos e fale conosco pelo WhatsApp.",whatsapp:"",password:"123456"},products:[]};data.settings.password??="123456";let editing=null;
const $=id=>document.getElementById(id);function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function renderList(){$("adminProducts").innerHTML=data.products.map(p=>`<div class="admin-item"><img src="${p.image||"https://via.placeholder.com/100"}"><div class="grow"><b>${p.name}</b><br>${Number(p.price).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})} · ${p.status}</div><button onclick="edit('${p.id}')">Editar</button></div>`).join("")||"<p>Nenhum produto cadastrado.</p>"}
function open(p){editing=p?.id||null;$("modalTitle").textContent=editing?"Editar produto":"Novo produto";$("pName").value=p?.name||"";$("pPrice").value=p?.price||"";$("pCategory").value=p?.category||"";$("pImage").value=p?.image||"";$("pDescription").value=p?.description||"";$("pStatus").value=p?.status||"Disponível";$("deleteProduct").classList.toggle("hidden",!editing);$("modal").classList.remove("hidden")}
window.edit=id=>open(data.products.find(p=>p.id===id));$("newBtn").onclick=()=>open();$("closeModal").onclick=()=>$("modal").classList.add("hidden");
$("saveProduct").onclick=()=>{let p={id:editing||Date.now().toString(),name:$("pName").value.trim(),price:Number($("pPrice").value)||0,category:$("pCategory").value.trim(),image:$("pImage").value.trim(),description:$("pDescription").value.trim(),status:$("pStatus").value};if(!p.name)return alert("Informe o nome.");if(editing)data.products=data.products.map(x=>x.id===editing?p:x);else data.products.push(p);save();renderList();$("modal").classList.add("hidden")};
$("deleteProduct").onclick=()=>{if(confirm("Excluir este produto?")){data.products=data.products.filter(p=>p.id!==editing);save();renderList();$("modal").classList.add("hidden")}};
$("loginBtn").onclick=()=>{if($("password").value===data.settings.password){$("login").classList.add("hidden");$("dashboard").classList.remove("hidden");loadSettings();renderList()}else $("loginMsg").textContent="Senha incorreta."};
function loadSettings(){$("sName").value=data.settings.name;$("sTitle").value=data.settings.title;$("sText").value=data.settings.text;$("sWhatsapp").value=data.settings.whatsapp}
$("saveSettings").onclick=()=>{data.settings={...data.settings,name:$("sName").value,title:$("sTitle").value,text:$("sText").value,whatsapp:$("sWhatsapp").value,password:$("sPassword").value||data.settings.password};save();$("saved").textContent="Salvo com sucesso.";setTimeout(()=>$("saved").textContent="",2000)};
document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("productsTab").classList.toggle("hidden",b.dataset.tab!=="products");$("settingsTab").classList.toggle("hidden",b.dataset.tab!=="settings")});
document.querySelector('[data-tab="products"]').classList.add("active");